[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"
authors = ["peter584aa <peter584aa@naver.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
